"""Render docs/production-evidence.json as the §26 report.

Every chain value in the output comes from the JSON, which
`prove_lifecycle.py` built from chain reads. Beyond formatting, this script
adds only fixed text stating how the run was driven (a script-held key,
not a browser wallet) — it cannot introduce a value the chain did not
return.

    python scripts/render_evidence.py
"""
import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[1]
SRC = REPO / "docs" / "production-evidence.json"
OUT = REPO / "docs" / "production-evidence.md"


def main() -> None:
    r = json.loads(SRC.read_text(encoding="utf-8"))
    lines = [
        "# Production lifecycle evidence",
        "",
        "Generated by `scripts/prove_lifecycle.py` from chain reads. Re-check it",
        "against the network yourself:",
        "",
        "```bash",
        "python scripts/prove_lifecycle.py --verify docs/production-evidence.json",
        "```",
        "",
        "| | |",
        "|---|---|",
        f"| Production contract | `{r['production_contract']}` |",
        f"| Network | {r['network']} |",
        f"| Chain ID | {r['chain_id']} |",
        f"| RPC | `{r['rpc']}` |",
        f"| Contract version | {r['contract_version']} |",
        f"| ABI | the schema the chain reports for the contract (`gen_getContractSchema`); "
        "its code is byte-verified against this repository by `scripts/check_docs.py` |",
        f"| Signer | `{r['signer']}` |",
        "| Wallet provider | none — every write was signed by `genlayer_py` with a key held by the script |",
        f"| Claim | `{r['claim_id']}` |",
        f"| Run | {r['started_at']} → {r['generated_at']} |",
        "",
        "**What this run does not cover.** It proves the protocol's lifecycle on",
        "the production contract, through real consensus and real finality. It",
        "does not pass through a browser wallet or the hosted frontend. The",
        "wallet path — the selected EIP-6963 provider being the one that signs,",
        "and reads and writes carrying the same contract — is covered by",
        "`frontend/tests/wallet-provider.test.ts` and `frontend/tests/config.test.ts`.",
        "The hosted site is covered by the live-site check in `docs/deployment.md`.",
        "",
        "**Two different kinds of \"final\" appear below, and they are kept apart.**",
        "`accepted` is the validators' decision; `finalized` is GenLayer",
        "transaction finality, after the appeal window. Separately, the claim",
        "reaches `FINALIZED` in the protocol only once its own challenge window",
        "has closed against a consensus-observed clock.",
        "",
        "## Transactions",
        "",
    ]
    for s in r["steps"]:
        a = s["accepted"]
        st = s.get("refreshed_state") or {}
        lines += [
            f"### {s['step']}",
            "",
            "```text",
            f"function:           {s['function']}",
            f"caller:             {s['caller']}",
            f"tx:                 {s['tx_hash']}",
            f"GenLayer tx id:     {a.get('gl_tx_id')}",
            f"submitted:          {s['submitted_at']}",
            f"decision:           {a.get('status_name')} · {a.get('consensus_result')}"
            f"  (votes: {', '.join(a.get('validator_votes') or []) or '—'})",
            f"execution:          {a.get('execution_result')}"
            + (f"  — {a.get('payload')}" if a.get("execution_result") != "SUCCESS" else ""),
            f"finality:           {s['finalized'].get('status_name')} at {s['finalized'].get('at')}",
        ]
        if st:
            lines.append(
                f"refreshed state:    {st.get('status')} · v{st.get('current_version')}"
                f" · verdict {st.get('current_verdict') or '—'}"
                f" · evidence {st.get('evidence_count')}"
                f" · challenges {st.get('challenge_count')}")
        lines += ["```", ""]
        if s["step"] == "FINALIZE_EARLY_REFUSED":
            lines += [
                "This transaction is recorded on purpose. It is the consensus",
                "clock refusing to end the challenge window early: the validators",
                "read the time themselves and the contract rejected the call.",
                "",
            ]

    v = r["verification"]
    lines += [
        "## Attestation",
        "",
        "```text",
        f"attestation:        {r['attestation'].get('attestation_id')}",
        f"verdict:            {r['attestation'].get('verdict')}",
        f"claim version:      v{r['attestation'].get('claim_version')}",
        f"adjudication:       {r['attestation'].get('adjudication_id')}",
        f"content binding:    {r.get('content_binding_hash')}",
        f"verify_attestation: valid={v.get('valid')} — {v.get('reason')}",
        "```",
        "",
        "## What each round read",
        "",
        "| Evidence | Retrieval | Content digest |",
        "|---|---|---|",
    ]
    for b in r.get("content_bindings") or []:
        lines.append(f"| `{b['evidence_id']}` | {b['retrieval']} | "
                     f"`{(b['digest'] or '—')[:32]}{'…' if b['digest'] else ''}` |")
    lines += [
        "",
        "## Version history",
        "",
        "| Version | Verdict | Adjudication | Superseded |",
        "|---|---|---|---|",
    ]
    for h in r["history"]:
        lines.append(f"| v{h['claim_version']} | {h['verdict']} | "
                     f"`{h['adjudication_id']}` | {h['superseded']} |")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
